//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTestDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int eLoginId { get; set; }
        public string eFirstName { get; set; }
        public string eLastName { get; set; }
        public string eEmail { get; set; }
        public string eUsername { get; set; }
        public string ePassword { get; set; }
        public string eConfirmPassword { get; set; }
        public string Role { get; set; }
        public string OTP { get; set; }
    }
}
