//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTestDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSkill
    {
        public int skId { get; set; }
        public string skName { get; set; }
        public Nullable<long> skExperience { get; set; }
        public string skPrevProjects { get; set; }
        public string skCurrentProject { get; set; }
        public string skDomain { get; set; }
        public string skUsername { get; set; }
    }
}
